//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genders
    {
        public Genders()
        {
            this.Students = new HashSet<Students>();
        }
    
        public int GenderID { get; set; }
        public string GenderName { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<Students> Students { get; set; }
    }
}
